/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gbalmpfkuiyywujlhbbw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYWxtcGZrdWl5eXd1amxoYmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNDQ4OTUsImV4cCI6MjA3NzkyMDg5NX0.Nsd42ueS_3kby-XBr-Fsvo92RRIBIm55Hm3z0iZ12Tw"